on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'  # Set Go version

      # Build the binary
      - name: Build binary
        run: |
          mkdir -p ./bin
          GOOS=linux GOARCH=amd64 go build -o bin/ruuvi_mqtt_bridge-linux-amd64 ./src
          GOOS=darwin GOARCH=amd64 go build -o bin/ruuvi_mqtt_bridge-darwin-amd64 ./src

      - uses: googleapis/release-please-action@v4
        with:
          release-type: go

      # Upload Release Assets (binaries)
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/ruuvi_mqtt_bridge-linux-amd64
            bin/ruuvi_mqtt_bridge-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
