name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set environment
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build
        run: |
          mkdir -p bin
          go build -o bin/ruuvi_mqtt_bridge-${{ matrix.goos }}-${{ matrix.goarch }} ./src

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/ruuvi_mqtt_bridge-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
